baseURL = "https://blog2.thomaslevesque.net/"
languageCode = "en-us"
title = "Thomas Levesque's .NET Blog"
theme = "mainroad"
publishDir = "../blog"
googleAnalytics = "UA-31621259-1"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

[permalinks]
  posts = "/:year/:month/:day/:title/"

# Mainroad theme settings

[Author] # Used in authorbox
  name = "Thomas Levesque"
  bio = "Thomas Levesque is a French software developer from Paris."
  avatar = "images/avatar.jpg"

[Params]
  subtitle = "Tips, tricks and thoughts about .NET development"
  description = "Tips, tricks and thoughts about .NET development"
  copyright = "Thomas Levesque"
  authorbox = true
  opengraph = true
  twitter_cards = true
  post_meta = ["date" ]
  pager = true
  customCSS = ["css/social.css"]

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "social", "recent", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false
  tags_num = 15

[Params.widgets.social]
  github = "thomaslevesque"
  twitter = "thomaslevesque"
