baseURL = "https://blog2.thomaslevesque.net/"
languageCode = "en-us"
title = "Thomas Levesque's .NET Blog"
theme = "ananke"
publishDir = "../blog"

[permalinks]
  posts = "/:year/:month/:day/:title/"
