baseURL = "https://blog2.thomaslevesque.net/"
languageCode = "en-us"
title = "Thomas Levesque's .NET Blog"
theme = "ananke"
publishDir = "../blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

[permalinks]
  posts = "/:year/:month/:day/:title/"
